WebShopDig/Controllers/AdminServiceController.cs
using Domain.DataModels;
using Domain.Enums;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBusinessLogic;
using WebBusinessLogic.ContextDB;
using WebBusinessLogic.Interfaces;
using WebShopDig.Models;

namespace WebShopDig.Controllers
{
    public class AdminServiceController : Controller
    {
        // GET: AdminService

        public IAdministration _administration;
        [HttpGet]
        public ActionResult CreateProduct()
        {
            UserContext db = new UserContext();
            ULaptop mark1 = new ULaptop();


            mark1.Mark = db.Marks.ToList();// Eroareeeeeeee

            return View(mark1);
        }





        [Authorize(Roles = "Administrator")]

        [HttpPost]
        public ActionResult CreateProduct(ULaptop laptop, HttpPostedFileBase file)
        {
            var bl = new BusinessLogic();

            _administration = bl.GetAdministration();
            
            var entrydata = new LaptopModel();

            entrydata.productID = laptop.ProductID;
            entrydata.mark = laptop.Mark;
            entrydata.nameModel = laptop.NameModel;
            entrydata.processor = laptop.Processor;
            entrydata.frequency_processor = laptop.Frequency_processor;
            entrydata.dateTime = DateTime.Now;
            entrydata.modelRam = laptop.ModelRam;
            entrydata.capacityRam = laptop.CapacityRam;
            entrydata.cantitate = laptop.Cantitate;
            entrydata.added_by = User.Identity.Name;
            entrydata.image = laptop.imagePath;
            if (file !=null)
            {

                file.SaveAs(HttpContext.Server.MapPath("~/Images/") + file.FileName);
            }

            //var status = _administration.AdminAddLaptop(entrydata);
                return View();
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

WebShopDig/Controllers/LoginController.cs
using Domain.DataModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebBusinessLogic;
using WebBusinessLogic.Interfaces;
using WebShopDig.App_Start;
using WebShopDig.Models;

namespace WebShopDig.Controllers
{
    public class LoginController : BaseController
    {

        private readonly IAuthentification _session;
        public LoginController()
        {
            var bl = new BusinessLogic();
            _session = bl.GetLogin();
        }

        // GET: Login
       public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ULogin data)
        {
            var logindata = new LoginData();
            logindata.Username = data.Username;
            logindata.Password = data.Password;
            logindata.LoginDateTime = DateTime.Now;
            logindata.LoginIp = Request.UserHostAddress;

            var status = _session.UserAuthAction(logindata);
            if (status.Status == true)
            {
               
                var cookies = _session.GenerationCookie(data.Username + ":"+ data.Password);
                ControllerContext.HttpContext.Response.Cookies.Add(cookies);
                FormsAuthentication.SetAuthCookie(data.Username, true);


                //bool rool2 = Roles.Provider.IsUserInRole(data.Username, "Administrator");



                return RedirectToAction("Index", "Home");
            }
            else
            {

                ModelState.AddModelError("", status.Message);
                return View();
            }
                                  
        }

        public ActionResult LogOut ()
        {

            FormsAuthentication.SignOut();
            //ControllerContext.HttpContext.Response.Cookies.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

WebShopDig/Controllers/PageBuyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebShopDig.App_Start;

namespace WebShopDig.Controllers
{
    public class PageBuyController : BaseController
    {
        // GET: PageBuy
        //[AuthFilter]
        [Authorize]
        public ActionResult Products()
        {


           
            String[] roles = Roles.GetRolesForUser();
            return View();
        }
    }
}

WebShopDig/Views/Shared/_AdminLayout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>َPagina meniu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    @Styles.Render("~/bundles/mainstyle/css")
    @Styles.Render("~/bundles/mainstyle1/css")
    @Styles.Render("~/bundles/bootstrap/css")

    @Scripts.Render("~/bundles/popper/js")
    @Scripts.Render("~/bundles/bootstrap/js")

    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/validation/js")
    @RenderSection("scripts", required: false)


</head>
<body>



    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navba-header">

                <a class="navbar-brand" href="#">WebMaster</a>

            </div>
            <ul class="nav navbar-nav">
                <li>
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fa fa-align-justify"></i> <span>Meniu</span>
                    </button>
                </li>

                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li><a href="@Url.Action("Products","PageBuy")">PRODUCTS</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Administrator"))
                    {
                        <li><a href="#">Administration</a></li>
                        <li><a href="@Url.Action("Register", "Home")">Creare Produs</a></li>
                        <li><a href="#">Feedback</a></li>
                        <li><a href="#">Contact</a></li>
                    }
                    else
                    {
                        <li><a href="#">Promotii</a></li>
                        <li><a href="#">Feedback</a></li>
                        <li><a href="#">Contact</a></li>
                    }
                }

            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Hello, " + User.Identity.Name + "!", "Index", "Home", htmlAttributes: new { @class = "glyphicon glyphicon-user" })</li>
                    <li>@Html.ActionLink("LogOut", "LogOut", "Login", routeValues: null, htmlAttributes: new { @class = "glyphicon glyphicon-log-in" })</li>
                }
                else
                {

                    <li><a href="@Url.Action("Register", "Home")"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                    <li><a href="@Url.Action("Index", "Login")"><span class="glyphicon glyphicon-log-in"></span>Sign In</a></li>
                }
            </ul>
        </div>
    </nav>

    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Lista de produse</h3>
            </div>

            <ul class="list-unstyled components">
                <p>Test</p>
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Cărți</a>
                </li>

                <li>
                    <a href="#">View statistics</a>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Page</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">page1</a>
                        </li>
                        <li>
                            <a href="#">page2</a>
                        </li>
                        <li>
                            <a href="#">page3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Register", "Home")">Creare Produs</a>
                </li>
                <li>
                    <a href="#">Edit product/find</a>
                </li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="#" class="download">Descarca proiect</a>
                </li>
                <li>
                    <a href="#" class="article"> Biblioteca</a>
                </li>
            </ul>
        </nav>

        <div class="content">

            @RenderBody()



            <div class="line"></div>

        </div>




        @section Scripts {
            <script>
                $(document).ready(function () {
                    $('#sidebarCollapse').on('click', function () {
                        $('#sidebar').toggleClass('active');
                    });
                });
            </script>
        }



        <!-- /#wrapper -->
        <!-- Bootstrap core JavaScript -->



</body>



</html> 

WebShopDig/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>َPagina meniu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Add local styles, mostly for plugins css file -->
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}

    @Styles.Render("~/bundles/mainstyle/css")
    @Styles.Render("~/bundles/mainstyle1/css")
    @Styles.Render("~/bundles/bootstrap/css")

    @Scripts.Render("~/bundles/popper/js")
    @Scripts.Render("~/bundles/bootstrap/js")

    @Scripts.Render("~/bundles/jquery/js")
    @Scripts.Render("~/bundles/validation/js")
    @RenderSection("scripts", required: false)

    @model WebShopDig.Models.ULogin
</head>
<body>
    


    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navba-header">

                <a class="navbar-brand" href="#">WebMaster</a>

            </div>
            <ul class="nav navbar-nav">
                <li>
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fa fa-align-justify"></i> <span>Meniu</span>
                    </button>
                </li>

                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li><a href="@Url.Action("Products","PageBuy")">PRODUCTS</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Administrator"))
                    {
                        <li><a href="#">Administration</a></li>
                        <li><a href="@Url.Action("CreateProduct", "AdminService")">Creare Produs</a></li>
                        <li><a href="#">Promotii</a></li>
                        <li><a href="#">Feedback</a></li>
                        <li><a href="#">Contact</a></li>
                    }
                    else
                    {
                        <li><a href="#">Sports</a></li>
                        <li><a href="#">Promotii</a></li>
                        <li><a href="#">Feedback</a></li>
                        <li><a href="#">Contact</a></li>
                    }
                }

            </ul>

            <ul class="nav navbar-nav navbar-right">
                @if (User.Identity.IsAuthenticated)
                {
                <li>@Html.ActionLink("Hello, "+ User.Identity.Name+"!","Index", "Home",htmlAttributes: new { @class = "glyphicon glyphicon-user" })</li>
                <li>@Html.ActionLink("LogOut", "LogOut", "Login", routeValues: null, htmlAttributes: new { @class = "glyphicon glyphicon-log-in" })</li>
                }
                else
                {

                    <li><a href="@Url.Action("Register", "Home")"><span class="glyphicon glyphicon-user"></span>Sign Up</a></li>
                    <li><a href="@Url.Action("Index", "Login")"><span class="glyphicon glyphicon-log-in"></span>Sign In</a></li>
                }
            </ul>
        </div>
    </nav>

    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Lista de produse</h3>
            </div>

            <ul class="list-unstyled components">
                <p>Test</p>
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Cărți</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Cărți fantastice</a>
                        </li>
                        <li>
                            <a href="#">Cărți clasice</a>
                        </li>
                        <li>
                            <a href="#">Cărți online</a>
                        </li>
                    </ul>
                </li>

                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Page</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">page1</a>
                        </li>
                        <li>
                            <a href="#">page2</a>
                        </li>
                        <li>
                            <a href="#">page3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact Us</a>
                </li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="#" class="download">Descarca proiect</a>
                </li>
                <li>
                    <a href="#" class="article"> Biblioteca</a>
                </li>
            </ul>
        </nav>

        <div class="content">

            @RenderBody()



            <div class="line"></div>

        </div>




        @section Scripts {
            <script>
                $(document).ready(function () {
                    $('#sidebarCollapse').on('click', function () {
                        $('#sidebar').toggleClass('active');
                    });
                });
            </script>
        }



        <!-- /#wrapper -->
        <!-- Bootstrap core JavaScript -->



</body>



</html> 